title: Jaehyun Jeong
  name: Jaehyun Jeong
  email: jh0410636@unist.ac.kr
description: > 
  Jaehyun Jeong is

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:title

url: "https://jaehyun-j.github.io/" # the base hostname & protocol for your site
  
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima
